### ISSUE TITLE
Still not loading in

### ISSUE THREAD

**Issue by AdrianBruMoment** [samarthshrivas/LoFi-Converter-GUI#5]
It's not loading in :(

**Comment by samarthshrivas** [comment]
oh @AdrianBruMoment sry it again crashed.

**Comment by samarthshrivas** [comment]
@AdrianBruMoment i reloaded the app check !!

**Comment by AdrianBruMoment** [comment]
> @AdrianBruMoment i reloaded the app check !!

Thanks it works but can you try to add a setting for the amount of reverb or smth

**Comment by samarthshrivas** [comment]
![image](https://github.com/samarthshrivas/LoFi-Converter-GUI/assets/59404247/3ce471a4-ca30-4a07-9b43-609c830a3693)
@AdrianBruMoment Open this you will see bunch of settings

**Comment by AdrianBruMoment** [comment]
> ![image](https://user-images.githubusercontent.com/59404247/258652891-3ce471a4-ca30-4a07-9b43-609c830a3693.png) @AdrianBruMoment Open this you will see bunch of settings

Thankssssss

**Comment by samarthshrivas** [comment]
@AdrianBruMoment i will close this issue now!!
there is some cacheing error that's why its website is crashing, i will check the problem later.
dont try to convert very long youtube video (one hour above)
